//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConSignalR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comentario
    {
        public int id { get; set; }
        [Required]
        [StringLength(250)]
        public string texto { get; set; }
        [Required]
        [StringLength(50)]
        public string usuario { get; set; }
    }
}
